"""remove commented columns from patient_alerts

Revision ID: dc66ef445e1d
Revises: None
Create Date: 2026-03-17 00:19:24.167977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc66ef445e1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove commented columns from patient_alerts table
    op.drop_column('patient_alerts', 'case')
    op.drop_column('patient_alerts', 'title')
    op.drop_column('patient_alerts', 'message')
    op.drop_column('patient_alerts', 'status')
    op.drop_column('patient_alerts', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budii_alert_relationships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_alert_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('caregiver_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], name='budii_alert_relationships_caregiver_id_fkey'),
    sa.ForeignKeyConstraint(['family_id'], ['users.id'], name='budii_alert_relationships_family_id_fkey'),
    sa.ForeignKeyConstraint(['patient_alert_id'], ['patient_alerts.id'], name='budii_alert_relationships_patient_alert_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='budii_alert_relationships_pkey')
    )
    op.create_index('ix_budii_alert_relationships_patient_alert_id', 'budii_alert_relationships', ['patient_alert_id'], unique=False)
    op.create_index('ix_budii_alert_relationships_family_id', 'budii_alert_relationships', ['family_id'], unique=False)
    op.create_index('ix_budii_alert_relationships_caregiver_id', 'budii_alert_relationships', ['caregiver_id'], unique=False)
    op.create_table('patient_alerts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name='patient_alerts_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='patient_alerts_pkey')
    )
    op.create_index('ix_patient_alerts_patient_id', 'patient_alerts', ['patient_id'], unique=False)
    op.create_index('ix_patient_alerts_event_id', 'patient_alerts', ['event_id'], unique=False)
    op.create_table('geofence_breach_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('distance_meters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('breached_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name='geofence_breach_events_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='geofence_breach_events_pkey')
    )
    op.create_index('ix_geofence_breach_events_patient_id', 'geofence_breach_events', ['patient_id'], unique=False)
    # ### end Alembic commands ###
