"""Update medication_schedule table with detailed fields

Revision ID: 354f173625c1
Revises: 9a0b1c2d
Create Date: 2026-03-16 14:37:54.131909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '354f173625c1'
down_revision: Union[str, Sequence[str], None] = '9a0b1c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_device_tokens_device_token', table_name='user_device_tokens')
    op.drop_index('ix_user_device_tokens_user_id', table_name='user_device_tokens')
    op.drop_table('user_device_tokens')
    op.drop_index('ix_budii_alert_relationships_caregiver_id', table_name='budii_alert_relationships')
    op.drop_index('ix_budii_alert_relationships_family_id', table_name='budii_alert_relationships')
    op.drop_index('ix_budii_alert_relationships_patient_alert_id', table_name='budii_alert_relationships')
    op.drop_table('budii_alert_relationships')
    op.drop_index('ix_fcm_tokens_token', table_name='fcm_tokens')
    op.drop_index('ix_fcm_tokens_user_id', table_name='fcm_tokens')
    op.drop_table('fcm_tokens')
    op.drop_index('ix_notifications_agent_event_id', table_name='notifications')
    op.drop_index('ix_notifications_patient_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_geofence_breach_events_patient_id', table_name='geofence_breach_events')
    op.drop_table('geofence_breach_events')
    op.drop_index('ix_patient_geofence_patient_id', table_name='patient_geofence')
    op.drop_table('patient_geofence')
    op.drop_index('ix_patient_alerts_event_id', table_name='patient_alerts')
    op.drop_index('ix_patient_alerts_patient_id', table_name='patient_alerts')
    op.drop_table('patient_alerts')
    op.add_column('medication_schedules', sa.Column('name', sa.String(), nullable=False))
    op.add_column('medication_schedules', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('medication_schedules', sa.Column('prescription', sa.Text(), nullable=True))
    op.add_column('medication_schedules', sa.Column('schedule_type', sa.String(), nullable=False))
    op.add_column('medication_schedules', sa.Column('scheduled_times', sa.JSON(), nullable=False))
    op.add_column('medication_schedules', sa.Column('days_of_week', sa.JSON(), nullable=True))
    op.add_column('medication_schedules', sa.Column('meal_timing', sa.String(), nullable=True))
    op.add_column('medication_schedules', sa.Column('dosage_type', sa.String(), nullable=True))
    op.add_column('medication_schedules', sa.Column('dosage_count', sa.Integer(), nullable=True))
    op.drop_column('medication_schedules', 'scheduled_time')
    op.drop_column('medication_schedules', 'medicine_name')
    op.alter_column('messages', 'file_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('messages', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'sent'::character varying"))
    op.alter_column('messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_geofencing',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'location_boundary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'geofence_state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'inside'::character varying"))
    op.alter_column('users', 'geofence_outside_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'geofence_outside_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'geofence_state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'inside'::character varying"))
    op.alter_column('users', 'location_boundary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'is_geofencing',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'sent'::character varying"))
    op.alter_column('messages', 'file_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('medication_schedules', sa.Column('medicine_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('medication_schedules', sa.Column('scheduled_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('medication_schedules', 'dosage_count')
    op.drop_column('medication_schedules', 'dosage_type')
    op.drop_column('medication_schedules', 'meal_timing')
    op.drop_column('medication_schedules', 'days_of_week')
    op.drop_column('medication_schedules', 'scheduled_times')
    op.drop_column('medication_schedules', 'schedule_type')
    op.drop_column('medication_schedules', 'prescription')
    op.drop_column('medication_schedules', 'description')
    op.drop_column('medication_schedules', 'name')
    op.create_table('patient_alerts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name='patient_alerts_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='patient_alerts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_patient_alerts_patient_id', 'patient_alerts', ['patient_id'], unique=False)
    op.create_index('ix_patient_alerts_event_id', 'patient_alerts', ['event_id'], unique=False)
    op.create_table('patient_geofence',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('home_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('home_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('radius_meters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name='patient_geofence_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='patient_geofence_pkey')
    )
    op.create_index('ix_patient_geofence_patient_id', 'patient_geofence', ['patient_id'], unique=True)
    op.create_table('geofence_breach_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('distance_meters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('breached_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name='geofence_breach_events_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='geofence_breach_events_pkey')
    )
    op.create_index('ix_geofence_breach_events_patient_id', 'geofence_breach_events', ['patient_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alert_case', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recipient_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient_phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channel', postgresql.ENUM('sms', 'whatsapp', name='notification_channel_enum'), server_default=sa.text("'sms'::notification_channel_enum"), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('sent', 'failed', name='notification_status_enum'), autoincrement=False, nullable=False),
    sa.Column('twilio_sid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agent_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_patient_id', 'notifications', ['patient_id'], unique=False)
    op.create_index('ix_notifications_agent_event_id', 'notifications', ['agent_event_id'], unique=False)
    op.create_table('fcm_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fcm_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fcm_tokens_pkey')
    )
    op.create_index('ix_fcm_tokens_user_id', 'fcm_tokens', ['user_id'], unique=False)
    op.create_index('ix_fcm_tokens_token', 'fcm_tokens', ['token'], unique=True)
    op.create_table('budii_alert_relationships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_alert_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('caregiver_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], name='budii_alert_relationships_caregiver_id_fkey'),
    sa.ForeignKeyConstraint(['family_id'], ['users.id'], name='budii_alert_relationships_family_id_fkey'),
    sa.ForeignKeyConstraint(['patient_alert_id'], ['patient_alerts.id'], name='budii_alert_relationships_patient_alert_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='budii_alert_relationships_pkey')
    )
    op.create_index('ix_budii_alert_relationships_patient_alert_id', 'budii_alert_relationships', ['patient_alert_id'], unique=False)
    op.create_index('ix_budii_alert_relationships_family_id', 'budii_alert_relationships', ['family_id'], unique=False)
    op.create_index('ix_budii_alert_relationships_caregiver_id', 'budii_alert_relationships', ['caregiver_id'], unique=False)
    op.create_table('user_device_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_device_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_device_tokens_pkey')
    )
    op.create_index('ix_user_device_tokens_user_id', 'user_device_tokens', ['user_id'], unique=False)
    op.create_index('ix_user_device_tokens_device_token', 'user_device_tokens', ['device_token'], unique=True)
    # ### end Alembic commands ###
