"""Add messaging features

Revision ID: 1a2b3c4d
Revises: 
Create Date: 2026-03-09 15:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a2b3c4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to existing messages table
    op.add_column('messages', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('file_metadata', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('status', sa.Enum('sent', 'delivered', 'read', name='message_status'), nullable=False, server_default='sent'))
    op.add_column('messages', sa.Column('read_at', sa.DateTime(), nullable=True))
    
    # Create conversations table
    op.create_table('conversations',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('participants', postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=False),
        sa.Column('last_message_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('last_activity', sa.DateTime(), nullable=True),
        sa.Column('unread_counts', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop conversations table
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    
    # Remove new columns from messages table
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'status')
    op.drop_column('messages', 'file_metadata')
    op.drop_column('messages', 'file_url')
    
    # ### end Alembic commands ###
